name: build

on: push

jobs:
  build:
    if: |
      !startsWith(github.event.head_commit.message, 'ci') &&
      !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      if: startsWith(github.ref, 'refs/tags/') != true
      run: yarn build --publish never
    - name: Build and release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn build
    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/') != true
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: dist
