name: build

on: push

jobs:
  build:
    if: |
      !startsWith(github.event.head_commit.message, 'ci') &&
      !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: dist
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
         dist/*.AppImage
         dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
